name: salutation sur un jour quelquonque

on: workflow_dispatch

env:
  DAY_OF_WEEK: Lundi

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Gretting: Salut
    steps:
      - name: "Dit : Salut Cyril, nous sommes lundi"
        run: echo "$Gretting $First_Name. Nous sommes $DAY_OF_WEEK"
        env:
          First_Name: Cyril
