name: Récupération de la météo

on:
  push:
    branches:
      - main
    pull_request:
      types: [closed, assigned, opened, reopened]

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Récupération de la météo"
        run: curl wttr.in/$LOCATION
        env:
          LOCATION: Lyon
